/**
 * Dispatch SE1-02 — "Day Zero"
 *
 * Source: "SE1-02 — Day Zero — Draft 1" (Drive), revision ANLCKQkw9kWq12Z3smkK1X4jhaM8CswtMyzgSehpPj6RONoQkO90bxGvojlGmypnuygywTqVoMCGpPlBvYyKE4kXZn9ZthnGUunUjiUd1OU.
 * Synced after the 2026-09-13 story-flow and continuity pass.
 */

import type { Dispatch } from './dispatch-se1-01';

export const dispatchSE102: Dispatch = {
  code: 'SE1-02',
  title: 'Day Zero',
  season: 'Dispatch Two',
  setting: 'Accra, Ghana · 2048',
  status: 'Dispatch Two',
  scenes: [
    {
      id: "night-stop",
      heading: "The Midnight Stop",
      sub: "Three Weeks Before the Commissioning",
      paragraphs: [
        "Constable Constantine Bediako disliked cars that drove too slowly after midnight.",
        "Fast drivers were usually careless. Slow drivers were usually hiding something.",
        "The black sedan ahead of his patrol vehicle had been moving at half the legal speed for nearly two kilometres, drifting close to the shoulder whenever another vehicle approached. Its rear plate light was broken. One brake lamp flickered each time the driver touched the pedal. Constantine followed it through the quieter edge of East Legon, past unfinished towers and old family walls now trapped between clinics, apartment blocks and charging stations.",
        "The city had changed faster than most people admitted. Roads that had once flooded every rainy season now carried autonomous buses. Delivery drones crossed above churches and shrines. Children spoke to glasses that answered in voices more patient than their parents. On clear nights, orbital platforms moved across the sky like stars that had learned direction.",
        "Constantine did not consider all change evil. He was not foolish. Machines had saved lives, reduced traffic deaths and made policing easier. But somewhere along the way, people had stopped asking what should be built and begun asking only what could be built.",
        "He activated the patrol lights.",
        "The sedan continued another fifty metres before stopping beside a closed pharmacy. Constantine parked behind it and waited. The vehicle's system identified three occupants but returned no linked identity profile. Privacy shielding. Expensive, legal and always irritating.",
        "His partner, Corporal Yaw Danso, glanced up from the match replaying across his glasses. \"Broken plate light?\"",
        "\"And driving like a funeral procession.\"",
        "\"Maybe they are mourning.\"",
        "\"At this hour?\"",
        "\"People die at every hour.\"",
        "Constantine stepped out before Danso could continue. The night air carried heat from the pavement and the distant smell of charcoal smoke. He approached the driver's side with one hand near his holster.",
        "The driver lowered the window. He was a narrow-faced Japanese man in his forties wearing a grey collarless shirt. A white woman sat beside him, older, perhaps in her fifties, with silver threaded through her hair. In the rear seat, a younger man stared straight ahead.",
        "\"Good evening,\" Constantine said. \"Licence and vehicle authorization.\"",
        "The driver sent both to Constantine's police tablet. His authorization identified him as Kenji Sato, a robotics engineer attached to a multinational technology project in Ghana. Everything appeared valid.",
        "\"You know why I stopped you?\"",
        "\"The broken light,\" the driver replied.",
        "\"And your speed.\"",
        "\"We were talking.\"",
        "\"That usually does not prevent a vehicle from moving.\"",
        "The woman smiled slightly. \"Some conversations require slowness.\"",
        "Constantine looked at her. \"What conversation?\"",
        "The driver's hands tightened on the steering wheel. The woman answered before he could.",
        "\"The one everyone will be having soon.\"",
        "From the rear seat, the younger man said, \"They are opening the Baobab in three weeks. After that, there will be no pretending.\"",
        "The driver glanced at him sharply.",
        "Constantine had heard the name all month. Explorer 233's headquarters appeared on every news feed in Ghana. Politicians called it proof that Africa had entered the interstellar age. Critics called it a private empire disguised as a public dream. The company's founder, Laura Osei Baako, had become impossible to avoid. Her face appeared on buses, debates, school screens and protest signs.",
        "\"No pretending about what?\" Constantine asked.",
        "The younger man leaned forward. \"That the old world is already dead.\"",
        "\"Enough,\" the driver said.",
        "The woman continued to watch Constantine. \"Do you believe people should leave Earth, Officer Bediako?\"",
        "He had not given his name.",
        "His hand moved closer to his holster. \"How do you know who I am?\"",
        "The woman's eyes dropped to his chest, although his name strip was dark and unreadable from inside the vehicle. \"A policeman asks questions. That is his work.\"",
        "\"You did not answer mine.\"",
        "She reached slowly into the fold of her clothing. Constantine ordered her to stop. She did, then opened her empty hand.",
        "\"We are not your enemies,\" she said.",
        "\"That is for me to determine.\"",
        "The driver's authorization showed no warrants. The vehicle contained no prohibited materials. A scan found no weapons, no contraband and no outstanding alerts. Constantine could detain them for refusing to cooperate, but he had no offence beyond a broken light and suspicious conversation.",
        "The younger man laughed softly. \"The machine says we are clean, so we must be clean.\"",
        "Constantine turned toward him. \"Step out of the vehicle.\"",
        "The woman placed one hand on the dashboard. \"He is young. He mistakes provocation for courage.\"",
        "The rear passenger opened his door, but the woman told him to remain seated. Something in her voice made him obey immediately.",
        "She looked back at Constantine. \"You are asking the right questions. That is rare now.\"",
        "\"Which questions?\"",
        "\"What happens to people when machines remember everything? What happens to nations when the rich can escape the planet? What happens when humanity hears voices from the stars and assumes they are invitations?\"",
        "Constantine said nothing.",
        "The woman reached again, more slowly this time. He allowed it. She withdrew a small square of paper and held it through the window.",
        "Real paper. No embedded display, no identity tag, no visible code. Only a telephone number written in black ink.",
        "\"What is this?\" he asked.",
        "\"A conversation that cannot be recorded.\"",
        "He took the paper.",
        "The driver's broken lamp earned him a citation. Constantine ordered them to repair it before sunrise and watched the sedan disappear into the dark.",
        "When he returned to the patrol vehicle, Danso had paused the football match.",
        "\"What did they want?\"",
        "\"To talk.\"",
        "\"At midnight?\"",
        "\"People talk at every hour.\"",
        "Danso looked offended by the theft of his own joke.",
        "Constantine folded the paper twice and placed it inside his uniform pocket.",
        "He told himself he would throw it away at the station.",
        "He did not.",
      ],
    },
    {
      id: "the-shrine",
      heading: "The Shrine",
      art: { src: "/images/dispatch-two/shrine.png", alt: "A police constable sits before a small ancestral shrine in his bedroom" },
      paragraphs: [
        "Constantine lived alone in a narrow house his mother had left him near Adenta. The neighbourhood had grown around it without permission. New apartment blocks rose behind old walls. A solar tower cast moving shadows across the street each morning. Across from his gate, a shop sold imported service robots beside carved stools and funeral cloth.",
        "Inside his bedroom, the modern world stopped.",
        "The room held no listening system. The wall display remained disconnected unless he chose to use it. In the corner stood a small wooden shrine covered with white cloth. A brass bowl held water. Beside it rested kola nuts, a bottle of schnapps, cowries and a photograph of his grandfather in police uniform.",
        "Constantine changed from his uniform, washed his hands and sat before the shrine. He poured a small measure of drink onto the floor and spoke the names of the dead quietly. His grandmother had taught him that forgetting the ancestors did not make a person modern. It only made him alone.",
        "The paper waited on the table behind him.",
        "He ignored it while he ate. He ignored it while the news replayed Laura Osei Baako touring the unfinished Baobab. He ignored it through an argument between a planetary scientist and a preacher who claimed the signals were spirits testing humanity. He ignored it until a report showed families applying for permanent work on Mars and a company advertising child-sized pressure suits for settlers.",
        "Then he muted the screen.",
        "His grandfather had believed the future would make Ghana stronger. Constantine wondered what he would have thought of a future in which people dreamed of abandoning the soil beneath their own feet.",
        "He unfolded the paper.",
        "The number contained only seven digits.",
        "No country code. No network prefix.",
        "He used an old handset kept in a drawer, one with a removable battery and no biometric lock. The call connected without ringing.",
        "A woman answered and gave her name before he could speak. \"Claire Whitmore.\"",
        "\"You took longer than expected, Constantine.\"",
        "He recognized the voice from the sedan.",
        "\"You knew I would call.\"",
        "\"We knew you would decide for yourself.\"",
        "\"What is this?\"",
        "\"An invitation.\"",
        "\"To what?\"",
        "\"A place where questions are still permitted.\"",
        "She gave him an address in the industrial outskirts of Tema and a time two nights later. Before he could ask anything else, the line disconnected.",
        "When Constantine checked the call history, no number appeared.",
      ],
    },
    {
      id: "the-circle",
      heading: "The Circle",
      art: { src: "/images/dispatch-two/the-circle.png", alt: "Masked Day Zero members stand in a circle inside an abandoned warehouse" },
      paragraphs: [
        "The address belonged to an abandoned textile warehouse surrounded by newer factories. Constantine arrived in plain clothes and parked two streets away. The moon was thin. Cargo vehicles moved on the distant motorway while the warehouse remained dark.",
        "A man waited beside a rusted side entrance. Constantine recognized the young passenger from the sedan.",
        "\"No uniform tonight,\" the man said.",
        "\"No foolish talking tonight?\"",
        "The young man smiled. \"We will see.\"",
        "He held out a wooden box. \"Everything electronic.\"",
        "Constantine placed his phone, police tablet, glasses and sidearm inside. The man raised an eyebrow at the weapon.",
        "\"You came prepared.\"",
        "\"I came as a police officer.\"",
        "\"Not inside.\"",
        "Constantine almost left. Then he remembered the woman saying questions were still permitted. He surrendered the gun.",
        "Beyond the door, a corridor had been lined with candles. The warehouse's power had been cut. No cameras watched the passage. No sensors followed his movement. The silence felt unnatural only because the world had become so full of machines humming in the background.",
        "The corridor opened into the main factory floor.",
        "More than a hundred people stood in a wide circle. Some wore work clothes. Others wore tailored suits, uniforms, medical scrubs or traditional cloth. Constantine recognized a television commentator, a university lecturer and the owner of a construction company that held government contracts. None acknowledged one another.",
        "At the centre of the circle burned a low fire inside an iron basin.",
        "Claire Whitmore stood beside it. An older Ghanaian woman in white cloth waited at the opposite side of the fire.",
        "Claire inclined her head toward the older woman. \"Professor Korkor.\" The woman stepped forward. \"Esi Korkor,\" she said. \"Tonight, you enter with the name the world gave you. Whether you leave with it depends on what you are willing to surrender.\"",
        "A masked figure emerged from the darkness behind her.",
        "The mask covered the entire face in black cloth. A single white zero stretched from the forehead toward the mouth. The design was crude enough to be handmade and precise enough to feel ancient.",
        "Others followed until twelve masked figures stood around the fire.",
        "Professor Korkor spoke of Day Zero without raising her voice. She did not call it a religion, a party or a revolution. It existed before the signals, she said, before orbital settlements and thinking machines. It had cells across nations and among people who agreed on little except one belief: humanity had confused invention with wisdom.",
        "\"We do not hate tools,\" Professor Korkor said. \"We reject surrender. A hammer does not decide where the house will stand. A machine should not decide who receives work, medicine, freedom or truth. Yet every year, more of the human soul is handed to systems owned by people we will never meet.\"",
        "Nobody applauded.",
        "\"The signals from the stars have accelerated the disease. Governments prepare weapons. Corporations purchase planets not yet reached. The wealthy build escape routes and call them exploration. Explorer 233 is not the beginning, but it is a door. Once opened, it will not close by itself.\"",
        "Constantine thought of Laura on the news, promising that Africa would arrive among the stars as a builder. He had admired the sentence despite himself. Now he wondered what exactly she intended to build there.",
      ],
    },
    {
      id: "the-mark",
      heading: "The Mark",
      art: { src: "/images/dispatch-two/dancers-and-mark.png", alt: "A Day Zero initiate stands within a ritual circle as masked figures move around him" },
      paragraphs: [
        "The young man from the sedan entered the circle first.",
        "A drum began somewhere in the darkness.",
        "Three small figures moved out from behind the masked leaders. At first Constantine thought they were children, but their faces were those of old men and women, their bodies compact and powerful. Bells were tied around their ankles. White clay marked their arms.",
        "They danced around the young man without touching him.",
        "The rhythm quickened. The fire bent sideways though there was no wind. Constantine felt pressure building behind his eyes. The dancers moved faster than their legs should have allowed, passing through the smoke and appearing on the other side of the circle.",
        "He searched for wires, projectors or hidden machines, then remembered there were none.",
        "The young man cried out.",
        "A white circle glowed beneath the skin of his wrist. It burned brighter, then darkened into a raised scar.",
        "One of the masked figures placed a folded black mask in his hands.",
        "The young man bowed his head.",
        "Others entered the circle. Each received the mark. Some trembled. One woman collapsed and was carried away. Nobody explained where the dancers had come from or why the fire followed them.",
        "When Constantine's turn came, he remained still.",
        "Professor Korkor faced him. \"You may leave.\"",
        "\"What happens if I do?\"",
        "\"You return to your life. You will remember this room. We will remember you.\"",
        "\"Is that a threat?\"",
        "\"No. Threats are promises made by frightened people.\"",
        "The drum continued.",
        "Constantine stepped into the circle.",
        "The dancers surrounded him. The bells at their ankles sounded like metal striking beneath water. One reached toward his chest but stopped without touching. The air smelled suddenly of wet earth, though the warehouse floor was dry concrete.",
        "A voice spoke behind Constantine's left ear in his grandfather's language.",
        "Do not kneel to what you do not understand.",
        "He turned. Nobody stood there.",
        "Pain tore through his wrist.",
        "Constantine clenched his teeth as light formed beneath his skin, drawing a circle in one unbroken line. For an instant, he saw darkness filled with distant stars. Then the stars began going out, one after another, until only the white circle remained.",
        "The vision vanished.",
        "A scar marked his wrist.",
        "Professor Korkor offered him a mask.",
        "\"Day Zero is not the end of the world,\" she said. \"It is the moment humanity remembers it can begin again.\"",
        "Constantine accepted the mask.",
      ],
    },
    {
      id: "ten-days",
      heading: "Ten Days Before the Commissioning",
      art: { src: "/images/dispatch-two/twelve-masks.png", alt: "Masked Day Zero members gather in a dark industrial space" },
      paragraphs: [
        "The mark did not hurt the way a wound should hurt.",
        "It surfaced instead, a low heat beneath the skin that came and went without warning, sharpest in moments that had nothing to do with Day Zero at all. Filling out an incident report. Standing in line for lunch. Once, absurdly, while Danso described a football match in exhaustive detail. Constantine learned to press his thumb against it under the table and wait.",
        "He told no one. He changed nothing about his shifts, his uniform, his patrol route. That was, he came to understand, the entire point of him. A masked man in a warehouse could be dismissed as theatre. A police constable who behaved exactly as he always had was something else, proof that Day Zero did not live only in basements and burned effigies, but inside the machinery meant to stop it.",
        "Claire found him twice more before the commissioning.",
        "The first time, she did not ask him to do anything. She sat across from him at a chop bar near the Circle interchange, ordered nothing, and asked about his grandfather. He found himself answering, the shrine, the police uniform in the photograph, the schnapps poured onto the floor for the dead. She listened the way Danso never did, and he hated how much that mattered to him.",
        "The second time, she handed him a folded cloth beneath the table. Inside was a compact pistol, unregistered, its serial number filed to nothing.",
        "\"Your service weapon has a history,\" she said. \"This one has none. When the day comes, it will not be your hands that are remembered. It will be no one's.\"",
        "He asked what he was meant to do with it before then.",
        "\"Nothing,\" she said. \"Carry it. Let it become ordinary in your pocket, the way the mark has become ordinary under your sleeve.\"",
        "He kept it wrapped inside a boot at the back of his closet, beside the shrine, and did not examine what it meant that the two objects now shared a shelf.",
        "Once, he almost told Danso everything. They were parked outside a shuttered filling station near midnight, the radio murmuring low, and the confession had risen as far as his throat before Danso asked, without looking up from his glasses, whether Constantine thought the new orbital tax would raise fuel prices again. The moment passed. Constantine answered about the tax instead, and understood, with something close to relief, that he had not been ready to lose the life confession would have cost him.",
        "He visited the shrine more often in those days, not less. He poured the drink, spoke his grandfather's name, and asked no question he expected an answer to. His grandfather had built a life inside the law because he believed the law, imperfect as it was, belonged to the people who obeyed it. Constantine no longer knew whether he believed that, or whether he simply missed believing it.",
        "The commissioning date arrived on every screen in the city before it arrived in his chest.",
      ],
    },
    {
      id: "commissioning-night",
      heading: "Commissioning Night",
      art: { src: "/images/dispatch-two/commissioning-night.png", alt: "The Baobab glows beneath fireworks during the Explorer 233 commissioning ceremony" },
      paragraphs: [
        "The Baobab opened beneath fireworks, music and the eyes of the world.",
        "Constantine watched the ceremony from a police operations room four kilometres away. His unit had been assigned to manage traffic, protest activity and public security around the headquarters. On one screen, Laura Osei Baako stood beneath a manufactured sky and declared that Africa would arrive among the stars as a builder, not a passenger.",
        "Several officers applauded.",
        "Constantine did not.",
        "His wrist itched beneath his sleeve.",
        "At 11:43 p.m., his old handset vibrated inside his locker. Only one message appeared.",
        "MIDNIGHT. SOUTH SERVICE ROAD. COME ALONE.",
      ],
    },
    {
      id: "the-return",
      heading: "The Return Begins",
      art: { src: "/images/dispatch-two/under-overpass.png", alt: "Constantine meets Claire Whitmore beneath an unfinished overpass at night" },
      paragraphs: [
        "He left the station through the vehicle yard and drove without lights for the final hundred metres. Claire Whitmore waited beneath an unfinished overpass.",
        "She carried a paper folder.",
        "\"The return begins tonight,\" she said.",
        "Inside the folder were photographs of five Explorer 233 scientists. Constantine recognized them from the commissioning broadcast. The first page belonged to Dr. Samuel Tetteh, a biologist responsible for evaluating life discovered beyond Earth.",
        "\"He left the Baobab twenty minutes ago,\" Claire said. \"He believes he is meeting someone who can provide access to restricted biological samples taken from Mars.\"",
        "\"Why him?\"",
        "\"Because he agreed to help Explorer 233 decide what forms of life may be used, contained or destroyed. He calls it preparation.\"",
        "Constantine closed the folder. \"You want him arrested?\"",
        "\"No.\"",
        "The answer rested between them.",
        "He looked at her. \"You recruit a police officer and your first command is murder.\"",
        "\"We did not recruit a police officer. We revealed a man who already knew the law and justice were not the same thing.\"",
        "\"If I refuse?\"",
        "\"You return the mask. The mark remains.\"",
        "The old road above them vibrated as a cargo truck passed.",
        "Claire stepped closer. \"Within the hour, Laura Osei Baako will receive our warning. Within twenty-four hours, one of her scientists must die. The world must understand that Day Zero does not perform for cameras.\"",
        "She handed him a small key.",
        "\"Stay exactly where you are afterward,\" she said. \"Do not run. Do not change your work. Doors will open.\"",
      ],
    },
    {
      id: "laboratory",
      heading: "The Laboratory",
      art: { src: "/images/dispatch-two/laboratory.png", alt: "Two men face one another inside an abandoned agricultural laboratory" },
      paragraphs: [
        "Dr. Samuel Tetteh arrived at the disused agricultural laboratory shortly after one in the morning. The nearest drone corridor ended three kilometres away, and the abandoned district's traffic sensors and security contracts had gone dark years ago.",
        "The building stood beyond the city's newer developments, surrounded by fields that had been abandoned after salt entered the groundwater. Constantine waited inside wearing his police jacket and no mask.",
        "Tetteh entered through a side door, holding a portable sample case. He stopped when he saw Constantine.",
        "\"Officer?\"",
        "\"Dr. Tetteh.\"",
        "\"Is there a problem?\"",
        "Constantine showed his badge. \"You received a message about restricted samples.\"",
        "Tetteh's expression changed. \"Who told you that?\"",
        "\"Explorer 233's network was compromised tonight.\"",
        "The scientist looked toward the exit. \"I should call Director Boateng.\"",
        "\"Your communications are being monitored.\"",
        "That part was probably true.",
        "Tetteh lowered his hand. He looked exhausted rather than afraid. \"I thought the message came from someone inside the Mars settlement. There are reports that biological data is being withheld from African research teams.\"",
        "\"And you came alone.\"",
        "\"I did not want to accuse anyone without evidence.\"",
        "Constantine studied him. Samuel Tetteh did not look like a man preparing to destroy the world. He looked like a scientist who had left a celebration because he believed someone was hiding information.",
        "\"You should not have come,\" Constantine said.",
        "Tetteh frowned. \"Officer, what is this?\"",
        "Constantine thought of the shrine in his bedroom. He thought of his grandfather warning him not to kneel before what he did not understand. He thought of the dancers, the vanishing stars and Laura's ship waiting to leave Earth.",
        "The future, he realized, was always built by people who insisted there was no time to hesitate.",
        "He reached into his jacket and drew the pistol Claire had given him.",
        "Tetteh raised both hands. \"Listen to me.\"",
        "\"I am listening.\"",
        "\"You do not have to do this.\"",
        "The sentence angered Constantine because it was true.",
        "A police officer learned quickly that most violence entered the world long before the weapon appeared. It began in decisions, permissions and stories people told themselves. By the time a gun was drawn, everyone involved believed the ending had already been chosen.",
        "Constantine fired once.",
        "The sound struck the empty laboratory and returned from every wall.",
        "Samuel Tetteh fell beside the sample case.",
        "For several seconds, Constantine stood without moving. Then he placed the weapon on a metal table and wiped the surfaces he had touched. He took nothing from the scientist except the Explorer 233 access card clipped inside his jacket.",
        "Outside, the city glowed beyond the dark fields.",
        "Constantine expected to feel transformed. Instead, he felt exactly like himself.",
        "That frightened him more.",
      ],
    },
    {
      id: "doors-open",
      heading: "Doors Open",
      art: { src: "/images/dispatch-two/doors-open.png", alt: "A uniformed officer approaches the illuminated entrance of the Baobab" },
      paragraphs: [
        "By sunrise, the murder had become the largest criminal investigation in Ghana.",
        "Explorer 233 sealed its headquarters. Police checkpoints appeared across Accra. News channels replayed Samuel Tetteh's biography beside images of the Day Zero mask. Laura Osei Baako cancelled every interview and met with security officials behind closed doors.",
        "Constantine reported for duty at seven.",
        "He answered questions about the night shift, submitted his service weapon for routine inspection and joined the search team assigned to the laboratory perimeter. Nobody asked why his wrist was bandaged. Nobody noticed that the spent casing recovered inside the building did not match his registered ammunition.",
        "At noon, a senior commander called him into a mobile operations office.",
        "\"You handled the commissioning protests well,\" the commander said. \"No unnecessary force. No public complaints. Explorer 233 has requested police support for an expanded protective unit.\"",
        "Constantine kept his face neutral.",
        "\"They specifically need officers with security clearance, clean disciplinary records and experience around the Baobab. You are being reassigned temporarily.\"",
        "\"To the headquarters?\"",
        "\"To Laura Osei Baako's security detail.\"",
        "Claire Whitmore had been right.",
        "Doors opened.",
        "That evening, Constantine passed through the Baobab's main gate wearing his uniform and carrying a badge that authorized him to enter areas the public would never see. Security systems scanned his face, his eyes and his police credentials, then welcomed him by name.",
        "Above the entrance, the Explorer 233 emblem caught the last sunlight.",
        "Constantine touched the scar beneath his sleeve and walked inside.",
      ],
    },
  ],
};
